name: CI/CD Docker Build & Push

# 1.1. Disparadores: Se ejecuta al hacer push a la rama main
on:
  push:
    branches: [ "main" ]

env:
  # Configuración de variables de entorno con tus datos
  DOCKER_REPO: fullstack-back 
  DOCKER_USERNAME: colmay2005

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Obtener código del repositorio
    - name: Checkout repo
      uses: actions/checkout@v4

    # 2. Loguear en Docker Hub (Requisito 1.3)
    # Usa los secrets que configuraste en el paso anterior
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Construir y subir imagen Docker (Requisito 1.2 y 1.3)
    # Genera el tag: colmay2005/fullstack-back:latest
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest